source:
  repoUrl: https://github.com/fabsys/k3s-virtualbox.git
  revision: main 

apps:
  - appName: metallb
    path: cluster/apps/metallb
    namespace: metallb-system
  - appName: ingress-nginx
    path: cluster/apps/ingress-nginx
    namespace: ingress-nginx
  - appName: hajimari
    path: cluster/apps/hajimari
    namespace: hajimari
  - appName: kuard
    path: cluster/apps/kuard
    namespace: kuard
  - appName: nginx-demo
    path: cluster/apps/nginx-demo
    namespace: nginx-demo
  - appName: gitlab-runner
    path: cluster/apps/gitlab-runner
    namespace: gitlab-runner
  - appName: nextcloud 
    path: cluster/apps/nextcloud
    namespace: nextcloud
