apiVersion: v1
name: gitlab-runner
version: 0.64.0
appVersion: 16.11.0
description: GitLab Runner
keywords:
  - git
  - ci
  - deploy
dependencies:
  - name: gitlab-runner
    version: 0.64.0
    repository: https://charts.gitlab.io
